[tool.poetry]
name = "randstr-plus"
version = "0.0.2"
description = "A more flexible string generator"
authors = ["Gary Tyler <mail@garytyler.com>"]
license = "MIT"
readme = 'README.md'
repository = "https://github.com/garytyler/randstr-plus"
homepage = "https://github.com/garytyler/randstr-plus"
packages = [{ include = "randstr_plus" }]
classifiers = [
    "Framework :: Pytest",
    "Environment :: Plugins",
    "Topic :: Software Development :: Testing",
    "Topic :: System :: Networking",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]

[tool.poetry.dependencies]
python = ">=3.6,<4.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
mypy = "^0.790"
isort = "^5.6.4"
pytest = "^6.1.2"
pytest-cov = "^2.10.1"

[build-system]
requires = ["poetry >= 1.1.4"]
build-backend = "poetry.masonry.api"
