[tool.poetry]
name = "hsc_instructions"
version = "0.4.0"
description = "Instruction encoding and decoding for the hsc (name TBD) isa"
authors = ["Bolun Thompson <abolunthompson@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/HomebrewSiliconClub/Processor/tree/master/tools/sources/hsc_instructions"
homepage = "https://github.com/HomebrewSiliconClub/Processor"
classifiers = ["Development Status :: 4 - Beta", "Intended Audience :: Developers", "Topic :: Software Development :: Libraries", "Typing :: Typed"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
