[tool.poetry]
name = "web_tools"
version = "0.3.5"
description = ""
authors = ["rgilfanov <rgilfanov@fix.ru>"]

[tool.poetry.dependencies]
python = "^3.9"
gino = "^1.0.1"
fastapi = "^0.61.1"
SQLAlchemy-JSONField = "^0.9.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
