[tool.poetry]
name = "lassi-ilakkanankal"
version = "1.0.6"
description = ""
authors = ["julienmalard <julien.malard@mail.mcgill.ca>"]
license = "AGPL-3.0-or-later"
packages = [
    { include = 'லஸ்ஸியிலக்கணங்கள்', from = 'மூலம்' }
]

[tool.poetry.dependencies]
python = "^3.8"
semantic-version = "^2.8.5"
lark = "^0.10.1"
lassi = "^0.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
